### PR TITLE
Add .svg for dancing goose logo. 

### PR DESCRIPTION
**Pull request by catherinemoresco**
Signed-off-by: Catherine Moresco <cmoresco@google.com>

### CODE REVIEW

**Comment by TomHennen** [comment]
Thanks Catherine!

I'll leave it to one of

@brunodom @david-a-wheeler @joshuagl @marklodato @mlieberman85 @trishankatdatadog @zakgreant

to approve

**Comment by 06kellyjac** [comment]
It doesn't particularly matter but do the commits have "signed-off-by" twice or is that just a GH mobile thing?

**Review by trishankatdatadog — APPROVED** [review]

**Comment by catherinemoresco** [comment]
> It doesn't particularly matter but do the commits have "signed-off-by" twice or is that just a GH mobile thing?

They do, it's my mistake--I initially did the signoff manually not realizing that the angle brackets had to be included, and when I followed the suggested steps to automatically resolve it was appended in the correct format. Should be fixed now!

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
@devmoran - will leave upto you to see how we can link in root README.md (and probably skip slsa.dev right ?)

**Pull request merged**
