### PR TITLE
Add gh-badges for SLSA L2.

### PR DESCRIPTION
**Pull request by godofredoc**
Flutter team has recently met all the requirements for SLSA L2 in one of their repositories and we would like to add the SLSA badge to the README file. Looking at the resources we could only find the badges for L3 and we used instructions from https://github.com/slsa-framework/slsa/tree/main/resources/assets/badges to generate the L2 badges.

### CODE REVIEW

**Comment by godofredoc** [comment]
@laurentsimon this is the PR for adding the SLSA L2 badges.

**Review by laurentsimon — APPROVED** [review]
Thanks!

**Comment by laurentsimon** [comment]
You will need to sign off your commits. Click the DCO pre-submit above to see how to do that.

**Comment by godofredoc** [comment]
> You will need to sign off your commits. Click the DCO pre-submit above to see how to do that.

Done!

**Comment by inferno-chromium** [comment]
@godofredoc - maybe can you add slsa level 1 and 4 badges in the dir as well while you are here :)

**Comment by godofredoc** [comment]
> @godofredoc - maybe can you add slsa level 1 and 4 badges in the dir as well while you are here :)

Sure, let me add them!

**Pull request merged**
