### PR TITLE
Fix relative path to example.md

### PR DESCRIPTION
**Pull request by s-spindler**
The link currently returns 404.

### CODE REVIEW

**Comment by abacchi** [comment]
Good find- I do see that it is a 404 in prod right now: https://slsa.dev/spec/example.md#vision-case-study

Am I missing something with your edit? It seems to also lead to 404 - https://deploy-preview-558--slsa.netlify.app/example.md#vision-case-study

**Comment by s-spindler** [comment]
Weird. I can't find other places in the repo where one md file links to another outside of the same directory. This might not be how jekyll works, though. I found this: https://jekyllrb.com/docs/liquid/tags/#links

I'll try those...

**Comment by s-spindler** [comment]
Yea, that wasn't it... One more try - if it doesn't work I'll close here, open an issue and let someone take over that actually knows jekyll.

**Comment by s-spindler** [comment]
Well, it works, but no idea if this is how you want to structure the site. Feel free to close if it doesn't make sense.

**Comment by lehors** [comment]
I agree the link should be fixed but I think we should keep the file outside a version specific folder as long as it applies to all versions.

**Comment by s-spindler** [comment]
> I went ahead and submitted PR #604.

Sorry, I didn't get around to replying earlier. Thanks for fixing it!

**Pull request closed without merging**
