### PR TITLE
nonspec: Add adityasaky as a maintainer

### PR DESCRIPTION
**Pull request by adityasaky**
I'm proposing myself as a maintainer for the SLSA spec. I've been active generally for some time now but have been more involved recently in the source track. Please let me know if there are concerns, thanks!

### CODE REVIEW

**Review by TomHennen — APPROVED** [review]
LGTM!!

**Review by mlieberman85 — APPROVED** [review]
Lgtm!

**Review by marcelamelara — APPROVED** [review]
Absolutely in favor of adding @adityasaky to the team :) Thanks for all your great work so far!

**Review by jkjell — APPROVED** [review]
I'm not a SLSA maintainer but, I am a huge fan of @adityasaky's work. This would be well deserved.

**Review by lehors — APPROVED** [review]

**Review by 06kellyjac — APPROVED** [review]

**Review by trishankatdatadog — APPROVED** [review]
💯 

(Sorry for late reply, PTO in an opposite time zone)

**Comment by lehors** [comment]
This has now been approved by a majority of the current maintainers. Merging.
Welcome to the club @adityasaky !

**Comment by adityasaky** [comment]
Thanks, all!

**Pull request merged**
