### PR TITLE
Terminology to do

### PR DESCRIPTION
**Pull request by jonvnadelberg**
Added TODO entries and definitions.  Alphabetized table entries.

### CODE REVIEW

**Comment by jonvnadelberg** [comment]
@olivekl Pull request for terminology page.

**Comment by joshuagl** [comment]
Hi @jonvnadelberg, I appreciate your efforts here! I haven't reviewed your changes in depth, because I think we might want to take a different approach to updating the terminology page.

The SLSA team have taken the position that if we can avoid defining a term, we should. In some cases we think we can remove a term by changing (throughout SLSA, not just on the terminology page) to use a term which is more widely recognised. 

A good example of this is package vs. artifact. We've had some discussion about this in https://github.com/slsa-framework/slsa/issues/520 and the Google Doc linked to from that issue. The conclusion we came to was that we should use "artifact" for the output of a build and "package name" (not just "package") only when "artifact" is not clear. This kind of terminology update/review is a much larger task than just ensuring everything is covered, but should greatly simplify things for readers of the SLSA spec.

When we do need to introduce new terms in the terminology page, it could make sense to introduce them in a sequential order that builds on prior defined terms. That way someone can get a complete understanding of new/special terms by reading the page (or section of the page) top-to-bottom.

The definition of all terms into a glossary-like page here makes me question the table layout, but perhaps that's less of a problem if we implement the two suggestions above.

What do you think?

**Comment by jonvnadelberg** [comment]
> Hi @jonvnadelberg, I appreciate your efforts here! I haven't reviewed your changes in depth, because I think we might want to take a different approach to updating the terminology page.
> 
> The SLSA team have taken the position that if we can avoid defining a term, we should. In some cases we think we can remove a term by changing (throughout SLSA, not just on the terminology page) to use a term which is more widely recognised.
> 
> A good example of this is package vs. artifact. We've had some discussion about this in #520 and the Google Doc linked to from that issue. The conclusion we came to was that we should use "artifact" for the output of a build and "package name" (not just "package") only when "artifact" is not clear. This kind of terminology update/review is a much larger task than just ensuring everything is covered, but should greatly simplify things for readers of the SLSA spec.
> 
> When we do need to introduce new terms in the terminology page, it could make sense to introduce them in a sequential order that builds on prior defined terms. That way someone can get a complete understanding of new/special terms by reading the page (or section of the page) top-to-bottom.
> 
> The definition of all terms into a glossary-like page here makes me question the table layout, but perhaps that's less of a problem if we implement the two suggestions above.
> 
> What do you think?

Hi @joshuagl 

I think if we are going to have a list of terms we wish to define on a page, that we put them in alphabetical order instead of sequential order because if people are going to a terminology page, they want the definition of a word or phrase, and the easiest way to find that is alphabetically.


A terminology page would be helpful to users when trying to understand what they are reading.  By not defining terms that we are using, it seems to me that we are obfuscating what we are talking about, making implementation less understandable and unclear.


Maybe instead of having the page as it currently exists, and glossary-like page would be helpful to users.  We should avoid explaining and re-explaining the same information on different pages where possible.

**Comment by MarkLodato** [comment]
I just sent out #629 which covers a lot of the changes here, except for "ecosystem" and "project." For those, I think we need a separate 'Package model' section with a bit more terms, rather than expanding the Overview section.

**Comment by MarkLodato** [comment]
Since this PR is out of date, I'll close it to avoid clutter. Feel free to open as separate PR.

**Pull request closed without merging**
