### PR TITLE
fix: code formatting color

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

The code text over the code background does not have enough contrast.

### CODE REVIEW

**Comment by asraa** [comment]
image


Text is readable now

**Review by laurentsimon — APPROVED** [review]

**Review by inferno-chromium — APPROVED** [review]
Minor color fix, fixing a user complaint, so merging.

**Comment by inferno-chromium** [comment]
There is more color breakage with highlighted words seeimage

**Comment by joshuagl** [comment]
We should probably revert this change until a fix is available.

**Comment by inferno-chromium** [comment]
> We should probably revert this change until a fix is available.

https://github.com/slsa-framework/slsa/pull/402

**Pull request merged**
