### PR TITLE
nonspec: Add TomHennen as a maintainer

### PR DESCRIPTION
**Pull request by TomHennen**
I'd like to propose making myself a maintainer.

I believe I meet the requirements [listed here](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer).

### CODE REVIEW

**Review by lehors — APPROVED** [review]
Yes!

**Review by joshuagl — APPROVED** [review]
Absolutely, thanks Tom!

**Review by mlieberman85 — APPROVED** [review]
Definite +1 from me

**Comment by lehors** [comment]
With support from a majority of Maintainers this is approved. Congrats @TomHennen !

**Comment by TomHennen** [comment]
Thanks all!

**Pull request merged**
