### PR TITLE
Add a scrollbar to the TOC sidebar when getting long

### PR DESCRIPTION
**Pull request by lehors**
It's been bugging me for a while and @ianlewis's comment on PR #626 gave me the incentive to try and fix it.
Someone more fluent than me in modern CSS and tailwindcss can probably do better than me (my CSS days go back to CSS2 circa 2008! :-) but I think this is already an improvement.

### CODE REVIEW

**Comment by lehors** [comment]
The effect is especially visible on the onepage version of the spec: https://deploy-preview-630--slsa.netlify.app/spec/v1.0/onepage

**Comment by MarkLodato** [comment]
This makes the ToC really small on larger screens (max height 384px). Should we wait for Psycle to fix this?

**Comment by lehors** [comment]
Ok, see if this is better now.

**Review by MarkLodato — APPROVED** [review]
I'm OK with this change as a temporary hack until Psycle has a proper fix. It improves desktop so that you can actually see the full TOC, while degrading mobile (causes unnecessary and confusing scrolling), which seems like an OK trade.

**Pull request merged**
