### PR TITLE
Create SECURITY.md# Security Policy  ## Supported Versions  Use this …

### PR DESCRIPTION
**Pull request by ijunxyz123**
…section to tell people about which versions of your project are currently being supported with security updates.  | Version | Supported          | | ------- | ------------------ | | 5.1.x   | :white_check_mark: | | 5.0.x   | :x:                | | 4.0.x   | :white_check_mark: | | < 4.0   | :x:                |  ## Reporting a Vulnerability  Use this section to tell people how to report a vulnerability.  Tell them where to go, how often they can expect to get an update on a reported vulnerability, what to expect if the vulnerability is accepted or declined, etc.
[PR title follows `<type>: <subject>`](https://github.com/slsa-framework/slsa/actions/workflows/conventional-commits.yml)https://github.com/slsa-framework/slsa/actions/workflows/conventional-commits.yml/badge.svghttps://github.com/slsa-framework/slsa/actions/workflows/conventional-commits.ymlijunxyz123:patch-1specification.mdthepetk:ft/add_security_policy

### CODE REVIEW

**Comment by marcelamelara** [comment]
This looks like a reputation farming attempt. I suggest we close this unless the author can provide reasoning for this change.

**Comment by lehors** [comment]
Adding a SECURITY.md file could be valuable but definitely not the way this PR is doing it.

**Review by albertanastasia — COMMENTED** [review]
ijunxyz123:patch-2

**Comment by albertanastasia** [comment]
.patch

**Review by albertanastasia — COMMENTED** [review]
SECURITY.md

**Comment by albertanastasia** [comment]
#574

**Comment by albertanastasia** [comment]
.patch

**Pull request closed without merging**
