### PR TITLE
Add Threat and Mitigations page.

### PR DESCRIPTION
**Pull request by MarkLodato**
The intention is to address #42 by describing specific attacks that must be addressed at each level to guide implementers.

The doc is not yet complete, but hopefully it is still of some use. It seems better to submit a mostly complete page rather than wait forever for me to finish it.

The page is linked from the "levels" page but not from the bar at the top. This is because it is (a) not really ready for general consumption and (b) not intended for most readers.

### CODE REVIEW

**Comment by TomHennen** [comment]
I do find this useful.

It's not quite clear to me how these various threats are protected against at these levels (maybe that's fine?).  Would it be worth numbering the requirements and then referencing them with these threats?  Maybe it would be too long a list.

**Comment by MarkLodato** [comment]
I'm working on an alternative format that will hopefully better address it. @joshuagl also mentioned that moving this to a separate doc is probably a good idea.

One thing that I think the detailed threat model can convey is how the notion of policy comes in - in other words, how to *use* the provenance to prevent specific attacks.

I'll send out an update once the next version is ready for review.

**Comment by MarkLodato** [comment]
Hey folks, I rewrote this to be much more exhaustive and explanatory. It's not yet complete, but I'm running out of time before my vacation (Aug 13 - Sep 13) so I wanted to get this draft out now. Please take a look to see if you find it useful or if you have any other feedback.

**Comment by TomHennen** [comment]
I'm not sure "(H) Use a bad package" needs to be outside the scope of SLSA.  Users _could_ define a policy for the packages they use.  That policy could indicate what acceptable builder & sources are used for this package.  That information _may_ provide enough context for the user to determine this isn't what they want.

**Comment by MarkLodato** [comment]
Hi @joshuagl would you mind reviewing this? Do you think it's valuable to submit in its current state rather than waiting until I have time to fully flesh it out?  I added an intro so hopefully it isn't quite so rough.

**Review by joshuagl — APPROVED** [review]
This looks great, thanks Mark!

Note that DCO bot is failing because 5f3edaca19ca550141ba4ea38f6e6c88c73a81f2 fails has a co-authored-by but no signed-off-by

**Comment by MarkLodato** [comment]
Thanks @joshuagl! DCO issue is fixed.

Any other feedback on this? @hixie you had wrote #34 and #35. Does this doc (or the existing page) address your original question?

**Comment by Hixie** [comment]
This is fantastic. I think for #34 and #35 it would be great to name those attacks specifically in this doc to make it clear to what extent and how those specific attacks are mitigated.

**Pull request merged**
