### PR TITLE
Fix link to faq

### PR DESCRIPTION
**Pull request by btharper**

### CODE REVIEW

**Review by 06kellyjac — COMMENTED** [review]
change is good, DCO check is failing:

`git commit --amend -signoff` or `git commit --ammend -s` to fix

https://wiki.linuxfoundation.org/dco

**Review by MarkLodato — APPROVED** [review]
Thanks for the fix! As mentioned, please amend the commit to include the `Signed-off-by` line to indicate your agreement to the DCO.

**Comment by btharper** [comment]
I'd mistakenly thought the DCO was essentially a CLA. Thanks for all the references. Updated now.

**Comment by david-a-wheeler** [comment]
I *do* accept that a DCO is a kind of "contributor agreement" - but the DCO is a special kind of contributor agreement that presents a low risk to project success. Other kinds of contributor agreements have a higher risk to project success, and contributor assignments (instead of agreements) present the highest risk to project success. See page 6-11 of my paper
[*Using an Open Source Software Approach for Cybersecurity Technology Transition*, David A. Wheeler, P-5279](https://www.ida.org/-/media/feature/publications/u/us/using-an-open-source-software-approach-for-cybersecurity-technology-transition/p-5279.ashx).

DCOs are a nice solution - they help reduce some legal concerns without significantly impeding normal development, especially since there are various tools to support them.

**Pull request merged**
