### PR TITLE
New Header/Menu Layout

### PR DESCRIPTION
**Pull request by mparsonspsycle**
### Structural changes
- New high level structure to facilitate left sidebar/drawer
- Main nav moved to sidebar/drawer
- Header now only visible on small screen widths

### Additional changes
- Main content sections (including heros) consolidated
- TOC column updated with scroll/fixed layout
- Content block layout issues fixed
- Spacer removed from main nav
- Main menu active highlighting (including adding current version to URL of "Provenance" and "VSA")

#### Please note:

The menu heirarchy config in `_nav.yml` uses links hardcoded with the various current docs versions. These links are used to power the "Main menu active highlighting" feature based on a users current URL.

This means that if/when you change the current versions of the Spec, Provenance and VAS docs (presumably on launch of `v1.0`), you will also need to update the `_nav.yml` config with URLs containing those new versions.

This will ensure that the main menu links always go to the correct current version, and that the active highlighting works for that version.

### CODE REVIEW

**Review by MarkLodato — APPROVED** [review]
This is great! Thank you!

I'll leave this PR open for a day or two to allow community members to comment.

**Review by lehors — APPROVED** [review]
Very nice improvement and it's nice to see crummy code being removed and the number of lines being reduced at the same time! :-)

**Comment by abacchi** [comment]
Looks good thank you!

**Review by abacchi — APPROVED** [review]

**Review by joshuagl — APPROVED** [review]
This is much nicer, thank you.

**Comment by inferno-chromium** [comment]
Some thing is up with page caching, for example i see the following broken top menu bar on a browser where i visited slsa.dev before. If I go from incognito, then it is all fine.

image

**Pull request merged**
