### PR TITLE
content: Add v1.1 without source track

### PR DESCRIPTION
**Pull request by lehors**
This is meant to include all the updates we have accumulated so far against 1.0, without any of the new levels or tracks. The goal is to publish this ASAP as a minor update to 1.0.

### CODE REVIEW

**Comment by TomHennen** [comment]
I've been trying to figure out how to best review the diff for this.

This URL is what I've come up with so far: https://github.com/lehors/slsa/compare/0f8e909%5E%5E..0f8e909

**Review by TomHennen — APPROVED** [review]
By comparing https://github.com/lehors/slsa/compare/0f8e909%5E%5E..0f8e909 and this PR this seems fine?

It's basically everything that was in v1.1 before minus the source track which is now 'draft'.  Seems fine?

**Comment by lehors** [comment]
> I've been trying to figure out how to best review the diff for this.
> 
> This URL is what I've come up with so far: https://github.com/lehors/slsa/compare/0f8e909%5E%5E..0f8e909

@MarkLodato actually wrote a script to compare the changes between two versions which is quite handy: https://github.com/slsa-framework/slsa/tree/main/docs#comparing-built-versions

**Comment by lehors** [comment]
> By comparing https://github.com/lehors/slsa/compare/0f8e909%5E%5E..0f8e909 and this PR this seems fine?
> 
> It's basically everything that was in v1.1 before minus the source track which is now 'draft'. Seems fine?

Yes, I created v1.1 by making a copy of the latest draft version (previously called v1.1) and removing the source track from it.

**Comment by TomHennen** [comment]
> > I've been trying to figure out how to best review the diff for this.
> > This URL is what I've come up with so far: https://github.com/lehors/slsa/compare/0f8e909%5E%5E..0f8e909
> 
> @MarkLodato actually wrote a script to compare the changes between two versions which is quite handy: https://github.com/slsa-framework/slsa/tree/main/docs#comparing-built-versions

Oh cool, TIL. :)

**Review by joshuagl — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
