### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ijunxyz123**
slsa.dev      ALIAS  apex-loadbalancer.netlify.com
www.slsa.dev  CNAME  slsa.netlify.appslsa.devwww.slsa.devapex-loadbalancer.netlify.com../tools/diff_site deploy-latest.zip deploy-preview.zipslsa.netlify.appdeploy-preview.zipdeploy-latest.zipnetlify dev -c 'bundle exec jekyll serve --livereload --incremental'# Prepare version A 
$ bundle exec jekyll build
$ mv _site _site.A
# Prepare version B
$ bundle exec jekyll build
$ mv _site _site.B
# Run the script
$ ../tools/diff_site _site.A _site.Bnetlify dev

### CODE REVIEW

**Review by ijunxyz123 — COMMENTED** [review]
ijunxyz123:patch-1

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
I don't think this is a correct change. You are just making the YAML frontmatter no longer work.

**Comment by marcelamelara** [comment]
This looks like a reputation farming attempt. I suggest we close this unless the author can provide reasoning for this change.

**Comment by lehors** [comment]
This PR has no value.

**Comment by albertanastasia** [comment]
albertanastasia:patch-1LICENSE.md

**Review by albertanastasia — COMMENTED** [review]
albertanastasia:patch-1LICENSE.md

**Pull request closed without merging**
