### PR TITLE
nonspec: Add trishankatdatadog to MAINTAINERS.md

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Following discussion with @TomHennen and @mlieberman85, I'd like to propose making myself a maintainer in order to expedite PR reviews.

I believe I meet the requirements [listed here](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer). Having said that, feel free to disagree!

### CODE REVIEW

**Review by TomHennen — APPROVED** [review]
Happy to have you!

**Review by mlieberman85 — APPROVED** [review]
Happy to have you

**Comment by trishankatdatadog** [comment]
Thank you very much! 🙂 

Let me request to join [this team](https://github.com/orgs/slsa-framework/teams/specification-maintainers).

Once I have joined, I think it's safe to merge this PR.

**Comment by mlieberman85** [comment]
I will add you once I get back to a computer with my yubikey

**Comment by mlieberman85** [comment]
Done!

**Review by lehors — APPROVED** [review]
It will be good to have you on board!

**Comment by lehors** [comment]
We have now reached the required majority of maintainers approving this proposal. So, I'm merging it.

**Pull request merged**
