### PR TITLE
Paragraphs, Unordered List and Ordered List Spacing

### PR DESCRIPTION
**Pull request by mparsonspsycle**
PR contains changes:
- Update paragraph spacing
- Update ordered/unordered list spacing
- Update ordered/unordered list bullets/number visibility
- Update ordered lists to use number, alpha and roman symbols when nested

Fixes https://github.com/slsa-framework/slsa/issues/335

### CODE REVIEW

**Review by joshuagl — APPROVED** [review]
I browsed the preview (including verifying the behaviour matches #335) and things look much better, thanks!

**Comment by mparsonspsycle** [comment]
@MarkLodato Understood. We’ll increase the spacings some more across the board.

Apologies, we didn’t realise there was a concept of “light” vs “loose” list spacing being used (we were going for as much consistency as possible across the board). I’ll get a specific override in place for the `<p>` in an `<li>` case too 👍

**Comment by MarkLodato** [comment]
> Apologies, we didn’t realise there was a concept of “light” vs “loose” list spacing being used (we were going for as much consistency as possible across the board). I’ll get a specific override in place for the `<p>` in an `<li>` case too 👍

Yup, this is a [Markdown thing](https://spec.commonmark.org/0.30/#loose). Thanks!

**Comment by mparsonspsycle** [comment]
@MarkLodato Morning Mark. I have updated the padding/margins to bring things more in line with the current live site again. Let me know if anything else jumps out at you.

**Review by MarkLodato — APPROVED** [review]
Thanks!

**Pull request merged**
