### PR TITLE
Switch from Google Analytics to GoatCounter.

### PR DESCRIPTION
**Pull request by MarkLodato**
It ends up that the "denied consent" mode doesn't work at all. It sends the data to Google but you can't actually view it on Google Analytics. Right now it's showing our site as having no traffic.

The only free, cloud-hosted, GDPR-compliant substitute I've found is GoatCounter. The site is super basic (see [demo](https://stats.arp242.net/)) but it's good enough. If we want something better, we'll need to either pay or self-host.

Once this is live, the analytics will be world-readable at https://slsa.goatcounter.com. After this PR is merged I'll invite steering committee members to be admins.

### CODE REVIEW

**Review by trishankatdatadog — APPROVED** [review]
I don't see major objections

**Comment by trishankatdatadog** [comment]
But @david-a-wheeler's voice is more critical here

**Comment by MarkLodato** [comment]
@david-a-wheeler Any objections? Or @trishankatdatadog is it OK to submit?

**Comment by trishankatdatadog** [comment]
> @david-a-wheeler Any objections? Or @trishankatdatadog is it OK to submit?

I have no objections but will refer to David

**Comment by MarkLodato** [comment]
> Can you give me a few more days to see if I can track down more info? I think this is a winner, but I'd like to track some things before we wrap this up. I expect this to be a good solution though.

Sounds good. No problem. Thanks!

**Comment by david-a-wheeler** [comment]
Let's do this! I talked with others who didn't see an issue.

Thanks for tracking down a better alternative for our situation.

**Review by david-a-wheeler — APPROVED** [review]

**Comment by MarkLodato** [comment]
Thanks for the thorough check!

**Pull request merged**
