### PR TITLE
nonspec: add zachariahcox to maintainers group

### PR DESCRIPTION
**Pull request by zachariahcox**
I'd like to propose making myself a maintainer, initially scoped to the source-track if needed!

I believe I meet the requirements [listed here](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer).

### CODE REVIEW

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Review by TomHennen — APPROVED** [review]
Happy to approve!

**Review by lehors — APPROVED** [review]
SGTM!

**Review by arewm — APPROVED** [review]
Certainly, thanks!

**Review by MarkLodato — APPROVED** [review]

**Comment by arewm** [comment]
Merging this PR as it has the majority of the current members.

**Pull request merged**
