### PR TITLE
Use vs Exfiltration: Provenance - Authenticated

### PR DESCRIPTION
**Pull request by pkmooreanaconda**
First swing at adding some text that separates illegitimate use of authentication-related material from exfiltration of said material.  Sebastien and I have been bouncing this back and forth a bit and wanted to get something out to drive discussion.

I think one thing that makes this text difficult is accounting for different mechanisms use different means to protect the provenance.  Were we just talking about digital signatures, it would be straightforward to say something that boils down to "don't let people steal or misuse the signing materials."  Keeping things generic means inventing a term like "authentication-related materials."  

This is related to issue #187

### CODE REVIEW

**Comment by mlieberman85** [comment]
Can you clarify the goal a bit?

**Comment by awwad** [comment]
I think there are two different conversations here.  Preston and I are primarily concerned with the signing scenario.  Existing text was written in such a way as to permit other means of data authentication.  (I suppose that that would include things like published hashes of provenance information, or transport authentication like TLS 🫤.)  Some of the ambiguous language in this PR is there to try not to interfere with this prior flexibility.

Our actual goal, though, is to clarity what seemed to us to be unclear when we were deciding on whether or not what we were up to met this criterion.  The existing text seems like it could **_include_** a system with completely unreachable keys but wide open access to make signing requests to those well-hidden keys (i.e. just signs whatever you throw at it) and **_exclude_** a system with reasonable key rotation mechanisms but better use-related protections.

**Comment by awwad** [comment]
I think there are two different conversations here. Preston and I are primarily concerned with the signing scenario. Existing text was written in such a way as to permit other means of data authentication. (I suppose that that would include things like published hashes of provenance information, or transport authentication like TLS 🫤).  Some of the ambiguous language in this PR is there to try not to interfere with this prior flexibility.

Our actual goal, though, is to clarify what seemed to us to be unclear when we were deciding on whether we meet this criterion.  The existing text seems like it could include a system with completely unreachable keys but wide open access to make signing requests to those well-hidden keys (i.e. just signs whatever anyone throws at it) and exclude a system with reasonable key rotation mechanisms but better use-related protections.

**Comment by arewm** [comment]
I feel like a lot of the comments here have already been addressed in the v1 specification as it currently is (i.e. provenance authenticity and accuracy with build system isolation). I think that questions/clarification around "best effort provenance completeness" and what should be included for the threat model at a build L3 are related to this and might be able to arrive at similarly interesting details and refinement.

**Comment by MarkLodato** [comment]
I'll close it for now to reduce clutter on the "open pull requests" page. Anyone feel free to pick this up and either reopen or create a new PR when ready for review.

**Pull request closed without merging**
