### PR TITLE
nonspec: remove Joshua as a maintainer

### PR DESCRIPTION
**Pull request by joshuagl**
I haven't been able to attend meetings or make time to review changes in some time, so it feels right that I stepp down.

Thanks so much for all the great collaboration. I will continue to advocate for SLSA and wish the project every success.

### CODE REVIEW

**Review by lehors — APPROVED** [review]
Sad, but thanks for being proactive about it and for all of your contributions.
Take care!

**Review by trishankatdatadog — APPROVED** [review]
Sorry to see you go, Joshua, and thanks for all your service 🫡

**Comment by trishankatdatadog** [comment]
Someone needs to remember to update the corresponding GH team(s).

**Review by arewm — APPROVED** [review]
Thanks for all that you have done. Maybe we will see you again in this space in the future.

**Review by marcelamelara — APPROVED** [review]
@joshuagl I'm sad to see you go, thank you for all of your contributions. Hopefully we'll get another opportunity to collaborate!

**Comment by TomHennen** [comment]
Very sorry to see you go Joshua!

**Review by TomHennen — APPROVED** [review]

**Comment by TomHennen** [comment]
I don't think there's any more reason to wait on merging this.  Thank you for all your help and guidance over the last few years @joshuagl!

**Pull request merged**
