### PR TITLE
Make source control recommended at L1

### LINKED ISSUE #127: Make Version Control required for SLSA Level1
I vote for making version control system a requirement for SLSA Level1.

In the [Source requirements](https://slsa.dev/requirements) section, none of the items is needed for Level1, whereas we could pick and choose from:
- using a source-control management system, 
- ensuring peer-review for pull requests (no direct pushes to the main/master branch),
- keeping the record of who did what by collecting logs
- ensuring MFA when logging to the  SCM

Of course I'm not proposing all these should go to L1, but instead could be spread between L1-L4 in a meaningful way.

### PR DESCRIPTION
**Pull request by TomHennen**
Fixes #127

Once this is in we can tag 0.1.

### CODE REVIEW

**Review by MarkLodato — APPROVED** [review]

**Review by inferno-chromium — APPROVED** [review]
I think you should also add 

“○” = RECOMMENDED 
in the text of that section so that people know meaning, i see you do this in other parts.

Thanks for making this change.

**Comment by TomHennen** [comment]
Done

**Comment by inferno-chromium** [comment]
Merging based on requirement satisfied as per this comment - https://github.com/slsa-framework/slsa/issues/127#issuecomment-920009556

**Review by nehtech9 — COMMENTED** [review]
🤖

**Review by Marco1981s — COMMENTED** [review]
App

**Pull request merged**
