### PR TITLE
content: Source Track Draft

### PR DESCRIPTION
**Pull request by Nikokrock**

### CODE REVIEW

**Comment by joshuagl** [comment]
Could you please rebase on the updated main branch and provide a brief description of the changes here? I can't quite tell from the history here where distinct changes are that differ from what landed in #1037. Sorry.

**Comment by TomHennen** [comment]
Per our discussion in the SLSA meeting today I'm going to set this to 'draft' since development is taking place elsewhere.  Let us know when to pick it up again?

**Comment by lehors** [comment]
Is there actually a chance we will resume work on this? I doubt it...

**Comment by zachariahcox** [comment]
I think we're ready to close this one. Thank you for the help @Nikokrock! You got things moving 👍

**Pull request closed without merging**
