### PR TITLE
Make the diagrams easier to edit

### PR DESCRIPTION
**Pull request by MarkLodato**
As part of #360, clean up the Figma diagrams to make them easier to maintain and to use a consistent visual style.

Major changes:

* Re-implement the "supply chain model" diagram in the same visual style as the other diagrams. (Previously it was made in Google Drawings and looked very different.)
* Rename "bad dependency/package" to "risky dependency/package" as per #347. (@ThomasOwens FYI)

Minor visual changes:

* Switch font to Inter, which is a Google Web Font, from Prodigy Sans. This allows editing without installing the font locally, in particular enabling editing on Linux and Chromebook.
* Make the Package → Dependencies arrow dashed (liked the Dependencies box) to hint that a Dependency is itself a package.
* Use the hexagonal Build shape consistently. (In some versions it was an oval.)
* Adjust various alignments and spacings for consistency.
* Use white background color consistency. (In some versions it was transparent, which renders poorly on GitHub with dark mode.)

Invisible cleanups:

* Refactor the Figma file so that it's easier to maintain, and update the instructions to better explain how to use it.
* Remove the fonts from our repo, since they are no longer needed.
* Remove unused PNG file.

### CODE REVIEW

**Comment by joshuagl** [comment]
Looks like we completely lost the labels on docs/images/supply-chain-threats.svg, was that intentional?
There's a typo in docs/images/supply-chain-model.svg – depedencies --> dependencies

**Comment by MarkLodato** [comment]
> Looks like we completely lost the labels on docs/images/supply-chain-threats.svg, was that intentional?

Reverted. It was intentional, but I shouldn't mix that into this refactoring PR. The diagrams are back to how they were before, and I'll send out a separate to consider removing them.

> There's a typo in docs/images/supply-chain-model.svg – depedencies --> dependencies

Thanks, fixed.

**Review by joshuagl — APPROVED** [review]
LGTM, thanks for tackling this!

**Comment by MarkLodato** [comment]
Thanks for the review!

**Pull request merged**
