### PR TITLE
:sparkles: update recent talk from Ian Lewis

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
This PR Proposes changes to add up the [recent talk from Ian Lewis](https://youtu.be/32IhwdAe0yI) about SLSA & guac in CloudNativeSecurityCon 2023 - Seattle

### CODE REVIEW

**Review by developer-guy — APPROVED** [review]
not a maintainer but LGTM

**Comment by di** [comment]
@ianlewis, is this OK with you?

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Comment by ianlewis** [comment]
> @ianlewis, is this OK with you?

Sure!

**Review by ianlewis — APPROVED** [review]

**Pull request merged**
