### PR TITLE
nonspec: Add Marcela as new SLSA spec maintainer

### PR DESCRIPTION
**Pull request by marcelamelara**
I'd like to self-nominate for maintainer status of the SLSA spec. I believe I meet the [criteria](https://github.com/slsa-framework/slsa/blob/main/MAINTAINERS.md#becoming-a-maintainer) for maintainer status. Thanks!

### CODE REVIEW

**Review by lehors — APPROVED** [review]
I'm all for it! We can certainly use the additional help given how several of us have been pulled into other things and can't dedicate as much time as we used to this project.

**Review by TomHennen — APPROVED** [review]
I fully support this!  Thanks for the proposal. :)

**Review by arewm — APPROVED** [review]
Thanks for all that you have been doing!

**Review by joshuagl — APPROVED** [review]
Thanks for self nominating. I wholeheartedly support this.

**Comment by marcelamelara** [comment]
Thank you all :)

**Pull request merged**
