### PR TITLE
Add a format selector to switch between onepage and multipage

### PR DESCRIPTION
**Pull request by lehors**
This change adds a format selector when a onepage exists so that the user can switch between formats.

### CODE REVIEW

**Comment by MarkLodato** [comment]
Thanks! This is helpful, but I'm concerned that that area is getting too crowded. See screenshot - almost the entire screen is filled with selectors rather than content.

Can we move it to the nav bar instead? That seems like a simpler solution and also avoids clutter in the main content area. FYI I have an upcoming PR to redo the nav bar on the left; I'm waiting for #694 to merge before sending.

image

**Comment by MarkLodato** [comment]
Here is my new PR, which includes the onepage in the nav bar: https://github.com/slsa-framework/slsa/pull/698

**Comment by lehors** [comment]
On what device to you get that view??
Of course there is always a trade-off with these things. Adding it to the navbar makes the navbar even longer... If it were up to me I would still go with having it the way this PR presents it but this isn't a hill I'm willing to die on either. :-)

**Comment by lehors** [comment]
I agree this a nice layout! (python.org)

**Comment by MarkLodato** [comment]
Shall we close this since we now have links in the left-hand bar?

**Comment by lehors** [comment]
I still like it better but ok.

**Pull request closed without merging**
